steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: '.'

  # Build the React app
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'
    env:
      - 'VITE_APP_API_BASE_URL=https://backend-service-704205683434.us-south1.run.app/v1'
      - 'VITE_APP_STORE_DOMAIN=https://crokete.com.mx'
      - 'VITE_APP_API_SOCKET_URL=https://backend-service-704205683434.us-south1.run.app'
      - 'VITE_APP_ADMIN_DOMAIN=https://admin.crokete.com.mx'
      - 'VITE_APP_CLOUD_NAME=dr397rg7u'
      - 'VITE_APP_CLOUDINARY_API_KEY=419969345985788'
      - 'VITE_APP_CLOUDINARY_API_SECRET=d4GnPnY66i38eXJISz9mslNV7C4'
      - 'VITE_APP_CLOUDINARY_UPLOAD_PRESET=crokete_upload_preset'
      - 'VITE_APP_CLOUDINARY_URL=https://api.cloudinary.com/v1_1/dr397rg7u/image/upload'
      - 'VITE_APP_MYMEMORY_API_KEY=a91efbf362a6e399453d'
      - 'VITE_APP_ENCRYPT_PASSWORD=856305f1a5b7ba87b8448e69b3bb7a4631c23f0afa2ca5331fa1373f7e372345'

  # Upload to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', './build', 'gs://crokete-admin']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
