const languages = [
  {
    _id: "67b2c768c349b30ded277f0b",
    status: "show",
    name: "German",
    code: "de",
    flag: "🇩🇪", // Germany

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
  {
    _id: "67b2c768c349b30ded277f0e",
    status: "show",
    name: "Urdu",
    code: "ur",
    flag: "🇵🇰", // Pakistan (Urdu)

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
  {
    _id: "67b2c768c349b30ded277f0a",
    status: "show",
    name: "English",
    code: "en",
    flag: "🇺🇸", // United States (English)

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
  {
    _id: "67b2c768c349b30ded277f0d",
    status: "show",
    name: "Hindi",
    code: "hi",
    flag: "🇮🇳", // India (Hindi)

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
  {
    _id: "67b2c768c349b30ded277f0c",
    status: "show",
    name: "Arabic",
    code: "ar",
    flag: "🇸🇦", // Saudi Arabia (Arabic)

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
  {
    _id: "67b2c768c349b30ded277f09",
    status: "show",
    name: "Bangla",
    code: "bn",
    flag: "🇧🇩", // Bangladesh

    createdAt: "2025-02-17T05:21:44.908Z",
    updatedAt: "2025-02-17T05:21:44.908Z",
  },
];

const languageList = [
  {
    name: "English",
    code: "en",
    native_name: "English",
    flag: "🇬🇧",
    rtl: false,
  },
  {
    name: "বাংলা",
    code: "bn",
    native_name: "বাংলা",
    flag: "🇧🇩",
    rtl: false,
  },
  {
    name: "العربية",
    code: "ar",
    native_name: "العربية",
    flag: "🇸🇦",
    rtl: true,
  },
  {
    name: "Español",
    code: "es",
    native_name: "Español",
    flag: "🇪🇸",
    rtl: false,
  },
  {
    name: "Français",
    code: "fr",
    native_name: "Français",
    flag: "🇫🇷",
    rtl: false,
  },
  {
    name: "Deutsch",
    code: "de",
    native_name: "Deutsch",
    flag: "🇩🇪",
    rtl: false,
  },
  {
    name: "中文",
    code: "zh",
    native_name: "中文",
    flag: "🇨🇳",
    rtl: false,
  },
  {
    name: "Русский",
    code: "ru",
    native_name: "Русский",
    flag: "🇷🇺",
    rtl: false,
  },
  {
    name: "Português",
    code: "pt",
    native_name: "Português",
    flag: "🇵🇹",
    rtl: false,
  },
  {
    name: "日本語",
    code: "ja",
    native_name: "日本語",
    flag: "🇯🇵",
    rtl: false,
  },
  {
    name: "हिन्दी",
    code: "hi",
    native_name: "हिन्दी",
    flag: "🇮🇳",
    rtl: false,
  },
  {
    name: "اردو",
    code: "ur",
    native_name: "اردو",
    flag: "🇵🇰",
    rtl: true,
  },
  {
    name: "ਪੰਜਾਬੀ",
    code: "pa",
    native_name: "ਪੰਜਾਬੀ",
    flag: "🇮🇳",
    rtl: false,
  },
  {
    name: "தமிழ்",
    code: "ta",
    native_name: "தமிழ்",
    flag: "🇮🇳",
    rtl: false,
  },
  {
    name: "Türkçe",
    code: "tr",
    native_name: "Türkçe",
    flag: "🇹🇷",
    rtl: false,
  },
  {
    name: "한국어",
    code: "ko",
    native_name: "한국어",
    flag: "🇰🇷",
    rtl: false,
  },
  {
    name: "Italiano",
    code: "it",
    native_name: "Italiano",
    flag: "🇮🇹",
    rtl: false,
  },
  {
    name: "Nederlands",
    code: "nl",
    native_name: "Nederlands",
    flag: "🇳🇱",
    rtl: false,
  },
  {
    name: "Polski",
    code: "pl",
    native_name: "Polski",
    flag: "🇵🇱",
    rtl: false,
  },
  {
    name: "Українська",
    code: "uk",
    native_name: "Українська",
    flag: "🇺🇦",
    rtl: false,
  },
  {
    name: "Tiếng Việt",
    code: "vi",
    native_name: "Tiếng Việt",
    flag: "🇻🇳",
    rtl: false,
  },
  {
    name: "ไทย",
    code: "th",
    native_name: "ไทย",
    flag: "🇹🇭",
    rtl: false,
  },
  {
    name: "فارسی",
    code: "fa",
    native_name: "فارسی",
    flag: "🇮🇷",
    rtl: true,
  },
  {
    name: "Bahasa Melayu",
    code: "ms",
    native_name: "Bahasa Melayu",
    flag: "🇲🇾",
    rtl: false,
  },
  {
    name: "Bahasa Indonesia",
    code: "id",
    native_name: "Bahasa Indonesia",
    flag: "🇮🇩",
    rtl: false,
  },
  {
    name: "עברית",
    code: "he",
    native_name: "עברית",
    flag: "🇮🇱",
    rtl: true,
  },
  {
    name: "Čeština",
    code: "cs",
    native_name: "Čeština",
    flag: "🇨🇿",
    rtl: false,
  },
  {
    name: "Svenska",
    code: "sv",
    native_name: "Svenska",
    flag: "🇸🇪",
    rtl: false,
  },
  {
    name: "Magyar",
    code: "hu",
    native_name: "Magyar",
    flag: "🇭🇺",
    rtl: false,
  },
  {
    name: "Suomi",
    code: "fi",
    native_name: "Suomi",
    flag: "🇫🇮",
    rtl: false,
  },
  {
    name: "Dansk",
    code: "da",
    native_name: "Dansk",
    flag: "🇩🇰",
    rtl: false,
  },
  {
    name: "Norsk",
    code: "no",
    native_name: "Norsk",
    flag: "🇳🇴",
    rtl: false,
  },
  {
    name: "Română",
    code: "ro",
    native_name: "Română",
    flag: "🇷🇴",
    rtl: false,
  },
  {
    name: "Српски",
    code: "sr",
    native_name: "Српски",
    flag: "🇷🇸",
    rtl: false,
  },
  {
    name: "Slovenčina",
    code: "sk",
    native_name: "Slovenčina",
    flag: "🇸🇰",
    rtl: false,
  },
  {
    name: "Hrvatski",
    code: "hr",
    native_name: "Hrvatski",
    flag: "🇭🇷",
    rtl: false,
  },
  {
    name: "Български",
    code: "bg",
    native_name: "Български",
    flag: "🇧🇬",
    rtl: false,
  },
  {
    name: "Ελληνικά",
    code: "el",
    native_name: "Ελληνικά",
    flag: "🇬🇷",
    rtl: false,
  },
  {
    name: "ქართული",
    code: "ka",
    native_name: "ქართული",
    flag: "🇬🇪",
    rtl: false,
  },
  {
    name: "አማርኛ",
    code: "am",
    native_name: "አማርኛ",
    flag: "🇪🇹",
    rtl: false,
  },
  {
    name: "नेपाली",
    code: "ne",
    native_name: "नेपाली",
    flag: "🇳🇵",
    rtl: false,
  },
  {
    name: "සිංහල",
    code: "si",
    native_name: "සිංහල",
    flag: "🇱🇰",
    rtl: false,
  },
  {
    name: "ភាសាខ្មែរ",
    code: "km",
    native_name: "ភាសាខ្មែរ",
    flag: "🇰🇭",
    rtl: false,
  },
  {
    name: "ລາວ",
    code: "lo",
    native_name: "ລາວ",
    flag: "🇱🇦",
    rtl: false,
  },
  {
    name: "မြန်မာ",
    code: "my",
    native_name: "မြန်မာ",
    flag: "🇲🇲",
    rtl: false,
  },
  {
    name: "Jawa",
    code: "jw",
    native_name: "Jawa",
    flag: "🇮🇩",
    rtl: false,
  },
  {
    name: "Basa Sunda",
    code: "su",
    native_name: "Basa Sunda",
    flag: "🇮🇩",
    rtl: false,
  },
  {
    name: "Tagalog",
    code: "tl",
    native_name: "Tagalog",
    flag: "🇵🇭",
    rtl: false,
  },
  {
    name: "Монгол",
    code: "mn",
    native_name: "Монгол",
    flag: "🇲🇳",
    rtl: false,
  },
  {
    name: "བོད་སྐད་",
    code: "bo",
    native_name: "བོད་སྐད་",
    flag: "🇨🇳",
    rtl: false,
  },
];

export { languages, languageList };
